version: "3.8"

services:
  aman_fastapi_app:
    build: .
    container_name: aman_fastapi_app
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - .env

  aman_proxy:
    image: caddy:latest
    container_name: aman_proxy
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - aman_caddy_data:/data
      - aman_caddy_config:/config
    depends_on:
      - aman_fastapi_app

volumes:
  aman_caddy_data:
  aman_caddy_config: